### ISSUE TITLE
zig build test reports error for zstbi

### ISSUE THREAD

**Issue by kamidev** [foxnne/aftersun#2]
```
➜  aftersun git:(main) zig build test
MachO Flush... error(link): undefined reference to symbol '_zstbiFree'
error(link):   first referenced in '/Users/jonas/src/zig/aftersun/zig-cache/o/5d3a28d0d6424b2cf904a5bb86c92c4d/stb_image.o'
error(link): undefined reference to symbol '_zstbiRealloc'
error(link):   first referenced in '/Users/jonas/src/zig/aftersun/zig-cache/o/5d3a28d0d6424b2cf904a5bb86c92c4d/stb_image.o'
error(link): undefined reference to symbol '_zstbiMalloc'
error(link):   first referenced in '/Users/jonas/src/zig/aftersun/zig-cache/o/5d3a28d0d6424b2cf904a5bb86c92c4d/stb_image.o'
error: UndefinedSymbolReference
error: test...
error: The following command exited with error code 1
```

Test envionment
```

➜  aftersun git:(main) zig version
0.10.0-dev.4418+99c3578f6
➜  aftersun git:(main) clang --version
Homebrew clang version 15.0.2
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
➜  aftersun git:(main) git log -1 | tee
commit 1814f6a43260e78fc93b28b936a0095c55eec714
Merge: 981e059 0ab4e8f
Author: foxnne <49629865+foxnne@users.noreply.github.com>
Date:   Sun Oct 16 21:32:44 2022 -0500

    Merge branch 'main' of https://github.com/foxnne/aftersun
```

**Comment by kamidev** [comment]
Building and running the app works fine. And commenting out the line below makes tests pass: 
```
  aftersun_tests.addPackage(zgui.pkg);
  //aftersun_tests.addPackage(zstbi.pkg);
  aftersun_tests.addPackage(zmath.pkg);

```
But if you use zstbi, this may be something to look into. I haven't properly debugged it yet.

**Comment by kamidev** [comment]
UPDATE: this has been fixed in the latest zig-gamedev.

**Comment by foxnne** [comment]
Thanks for the info! I'll update the zig-gamedev libs.

**Comment by foxnne** [comment]
Okay, I just pushed up the libs from zig-gamedev but it didn't seem to fix the issue, maybe I'm misunderstanding? Also it seems like something changed with zig-gamedev that makes my framerate uncapped (at least on Windows), I'll investigate all of these issues soon.

**Comment by michal-z** [comment]
Uncapped framerate is unexpected. Could you try to clear the cache before building?

**Comment by foxnne** [comment]
> Uncapped framerate is unexpected. Could you try to clear the cache before building?

![image](https://user-images.githubusercontent.com/49629865/197002938-c96af777-8957-4f2a-8d04-17eed9e60448.png)

Just cleared the cache and rebuilt, still getting nearly 500 fps.

**Comment by michal-z** [comment]
On my system (Windows 11, NVIDIA GTX 1660) I get 60 fps. Did you change your graphics driver recently or some graphics settings?

![image](https://user-images.githubusercontent.com/11540112/197009822-f3eb0034-726d-46b2-9c51-2d7cef560ca0.png)

**Comment by michal-z** [comment]
Note that you can force VSync setting in NVIDIA Panel. When I set it to 'Off` I also get ~600 fps.

![image](https://user-images.githubusercontent.com/11540112/197011631-412bdbd3-b2cb-47d1-8fc4-e7f9bf219aa4.png)

**Comment by foxnne** [comment]
Hmmm... Mine by default was set to: 

![image](https://user-images.githubusercontent.com/49629865/197012853-74a00a7a-11e4-4c3c-9caa-f77e51665831.png)

But even when I set it to "On", I still seem to be getting uncapped fps. I'll dig around and see if I can find out what's going on, likely an issue on my end. Thanks!

**Comment by michal-z** [comment]
Regarding `zstbi` test failure - you need to reference `zstbi` lib in `aftersun.zig`:

```zig
test {
    _ = zstbi; // <--------- This needs to be added
    _ = math;
    _ = gfx;
    _ = input;
    _ = time;
    _ = environment;
}
```

**Comment by foxnne** [comment]
Just pushed fix above, closing this issue.
